### ISSUE TITLE
Unnecessary 'sudo' in Dockerfile

### ISSUE THREAD

**Issue by ntpttr** [sedouard/fleet-bootstrapper#6]
In the example-app Dockerfile are the commands "RUN sudo apt-get install build-essential -y" and "RUN sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y". For me, the inclusion of 'sudo' made the script freeze - after I removed it it ran as intended.

**Comment by sedouard** [comment]
thanks! closed via https://github.com/sedouard/fleet-bootstrapper/commit/d4f881bce2f8eabc5389ff2cefbe9613a396d52a
